import test from 'node:test';
import assert from 'node:assert/strict';
import {sendStudioCode,studioOrigin,studioCodeEmail} from '../netlify/functions/_lib/studio-sign-in.mjs';
const config={configured:true,key:'test-only',from:'SayGday <hello@saygday.ai>'};
function database({member=true,admin=false,limited=false,error=false}={}){let links=0;return {get links(){return links;},rpc:async()=>({data:!limited}),from(table){const q={select(){return q},eq(){return q},limit(){return q},then(fn){return Promise.resolve({data:(table==='oo_portal_admins'?admin:member)?[{}]:[],error:error?{}:null}).then(fn)}};return q;},auth:{admin:{generateLink:async()=>{links++;return {data:{properties:{email_otp:'123456',hashed_token:'testhash'}}}}}}};}
test('CORS only accepts oo.studio and its own deploy previews',()=>{for(const origin of ['https://oo.studio','https://www.oo.studio','https://deploy-preview-95--oo-studio.netlify.app'])assert.equal(studioOrigin(origin),true);for(const origin of ['',null,'https://evil.example','https://oo.studio.evil.example','https://deploy-preview-1--other.netlify.app','null'])assert.equal(studioOrigin(origin),false);});
test('unknown address returns generic result without generating a code or sending mail',async()=>{const db=database({member:false});let calls=0;assert.deepEqual(await sendStudioCode({db,body:{email:'unknown@example.com'},ip:'test',configuration:config,fetchImpl:async()=>{calls++;}}),{sent:true});assert.equal(db.links,0);assert.equal(calls,0);});
test('registered client gets branded code using verified sender and idempotency key',async()=>{const db=database();let payload,headers;await sendStudioCode({db,body:{email:' CLIENT@example.com '},ip:'test',configuration:config,fetchImpl:async(url,options)=>{assert.equal(url,'https://api.resend.com/emails');payload=JSON.parse(options.body);headers=options.headers;return {ok:true};}});assert.equal(db.links,1);assert.equal(payload.from,'oo.studio <hello@saygday.ai>');assert.deepEqual(payload.to,['client@example.com']);assert.equal(payload.reply_to,'hello@oo.studio');assert.equal(payload.subject,'Your oo.studio sign-in code');assert.match(payload.text,/123456/);assert.equal(headers['Idempotency-Key'],'oo-sign-in-testhash');});
test('admin can sign in without client membership',async()=>{const db=database({member:false,admin:true});await sendStudioCode({db,body:{email:'hello@oo.studio'},ip:'test',configuration:config,fetchImpl:async()=>({ok:true})});assert.equal(db.links,1);});
test('rate limit, invalid address and unavailable membership lookup fail closed',async()=>{for(const [db,body] of [[database({limited:true}),{email:'a@example.com'}],[database(),{email:'bad'}],[database({error:true}),{email:'a@example.com'}]]){await assert.rejects(sendStudioCode({db,body,ip:'test',configuration:config,fetchImpl:async()=>{throw new Error('must not send')}}));assert.equal(db.links,0);}});
test('email provider failure is not reported as sent and never reveals provider details',async()=>{await assert.rejects(sendStudioCode({db:database(),body:{email:'a@example.com'},ip:'test',configuration:config,fetchImpl:async()=>({ok:false,status:500})}),e=>e.code==='EMAIL_UNAVAILABLE'&&!e.message.includes('test-only'));});
test('invalid generated codes never interpolate markup into email',()=>{assert.throws(()=>studioCodeEmail('<img src=x>'));});
